# Generated by Django 5.0.6 on 2024-06-25 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('pdescription', models.CharField(max_length=200)),
            ],
        ),
    ]
